import { Inter,Onest } from "next/font/google";
import "./globals.css";
import ParticleBg from "@/components/particleBg/ParticleBg";
import SmoothScroll from "@/components/smoothScroll/SmoothScroll";
import ToastContext from "@/context/ToastContext";
import AuthProvider from "@/context/AuthProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";

const inter = Inter({ subsets: ["latin"] });
const onest = Onest({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = getServerSession(authOptions)
  return (
    <html lang="en">
      <body className={`${inter.className} ${onest.className}`}>
        <AuthProvider>
        <ToastContext>
        <ParticleBg>
        {children}
        </ParticleBg>
        </ToastContext>
        </AuthProvider>
        </body>
    </html>
  );
}
