import { Inter,Onest } from "next/font/google";
import "./globals.css";
import ParticleBg from "@/components/particleBg/ParticleBg";
import SmoothScroll from "@/components/smoothScroll/SmoothScroll";
import ToastContext from "@/context/ToastContext";

const inter = Inter({ subsets: ["latin"] });
const onest = Onest({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${onest.className}`}>
        <ToastContext>
        <SmoothScroll />
        <ParticleBg>
        {children}
        </ParticleBg>
        </ToastContext>
        </body>
    </html>
  );
}
